### PR TITLE
Big http client refactor. Add integration tests.

### LINKED ISSUE #5: Retryable client sending empty payload on retries
It seems like the `RetryableClient` doesn't send a payload/sends an empty one when retrying a request.
Context: https://github.com/inception-project/inception/issues/2119#issuecomment-822020969

That is causing misleading exceptions/error messages and trouble when debugging INCEpTION <-> Pycaprio problems, as errors in the Swagger API are different than the ones `pycaprio` shows.

### PR DESCRIPTION
**Pull request by JavierLuna**
Fixes #5

HTTP client changes:

- Only GET operations are now retried
- Change retriable status codes to be more forgiving
- Fix how multipart form data was uploaded. There was an issue where the
  boundries were wrongly calculated and INCEpTION would freak out.
- Improve messages of API errors

Other changes:

- Add integration tests. They require an accessible **NON PROD**
  INCEpTION instance.
- Updated CONTRIBUTING to include instructions to run integs
- Remove old disclaimer from README. That situation is solved.
- Remove codecov orb that was making the CI fail. I'll fix it in another
  PR.

### CODE REVIEW

**Comment by reckart** [comment]
For some reason, the CI on this PR seems to have failed

**Comment by reckart** [comment]
Never mind, I see the comment on the CI in the PR description now ;)

**Comment by reckart** [comment]
In the instructions on how to install pycaprio, the readme still refers to the "current state of the project" section that was removed. So what is the plan going forward with respect to pypi?

**Comment by JavierLuna** [comment]
Everything is owned by me and latest version is on pypi already. I'll update the docs today, seems like a leftover, thanks

**Comment by reckart** [comment]
Great! I hadn't even noticed there already was a new release despite watching the repo for all notifications.

**Pull request merged**
